//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mClock.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_zh_CN {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_zh_CN() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mClock.Resources.AppResources.zh-CN", typeof(AppResources_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MClock_Title {
            get {
                return ResourceManager.GetString("MClock_Title", resourceCulture);
            }
        }
        
        internal static string MClock_Note1 {
            get {
                return ResourceManager.GetString("MClock_Note1", resourceCulture);
            }
        }
        
        internal static string MClock_Note2 {
            get {
                return ResourceManager.GetString("MClock_Note2", resourceCulture);
            }
        }
        
        internal static string MClock_Note3 {
            get {
                return ResourceManager.GetString("MClock_Note3", resourceCulture);
            }
        }
        
        internal static string MClock_Note4 {
            get {
                return ResourceManager.GetString("MClock_Note4", resourceCulture);
            }
        }
        
        internal static string MClock_Note5 {
            get {
                return ResourceManager.GetString("MClock_Note5", resourceCulture);
            }
        }
    }
}
